# Generated by Django 4.0 on 2022-02-28 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('resellerid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(max_length=30)),
                ('pid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('desp', models.TextField()),
                ('img', models.ImageField(upload_to='image')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('weightunit', models.CharField(max_length=12)),
                ('category', models.CharField(max_length=12)),
                ('subcategory', models.CharField(max_length=12)),
                ('vendor', models.CharField(max_length=12)),
                ('resellerf_k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.reseller')),
            ],
        ),
    ]
