# Generated by Django 4.0 on 2022-02-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='resellerf_k',
        ),
        migrations.DeleteModel(
            name='Reseller',
        ),
    ]
